networks:
  simple_dictionary_network:
    external: true

services:
  wss_app:
    build:
      context: .
      dockerfile: _docker/wss_app/Dockerfile
    container_name: wss_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./_docker/wss_app/entrypoint.sh:/usr/local/bin/entrypoint.sh
    networks:
      - simple_dictionary_network
    depends_on:
      - redis
      - mongo
    ports:
      - 8080
      - 8080

  redis:
    image: redis:alpine
    container_name: wss_redis
    networks:
      - simple_dictionary_network
    ports:
      - "6379:6379"

  mongo:
    image: mongo:8.0.15
    container_name: wss_mongo
    volumes:
      - ./tmp/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - simple_dictionary_network

